@Api_HostAddress = http://localhost:4006

### Crear rol
POST {{Api_HostAddress}}/api/rol
Content-Type: application/json
{
    "nombre": "admin"
}

### Modificar rol
PUT {{Api_HostAddress}}/api/rol/a5f86a17-16e3-4f65-9ddf-2d0bd933341d
Content-Type: application/json
{
    "habilitado": false
}

### Obtener todos los roles
GET {{Api_HostAddress}}/api/rol

### Obtener un rol específico
GET {{Api_HostAddress}}/api/rol/a9f86a17-16e3-4f65-9ddf-2d0bd933341d

### Crear usuario
POST {{Api_HostAddress}}/api/usuario
Content-Type: application/json
{
    "nombre": "Juan Pérez",
    "email": "juan.perez@example.com",
    "usuario": "juanperez",
    "pass": "securePassword123"
}

### Obtener todos los usuarios
GET {{Api_HostAddress}}/api/usuario

### Obtener usuario específico
GET {{Api_HostAddress}}/api/usuario/1

### Actualizar un usuario específico
PUT {{Api_HostAddress}}/api/usuario/1
Content-Type: application/json
{
    "email": "juan.perezsegundo@example.com",
    "usuario": "juanperez12",
    "pass": "daskdoa12"
}

### Asignar un rol a un usuario desde el controller Usuario
POST {{Api_HostAddress}}/api/usuario/1/rol/a5f86a17-16e3-4f65-9ddf-2d0bd933341d

### Quitar un rol a un usuario desde el controller Usuario
DELETE {{Api_HostAddress}}/api/usuario/1/rol/a5f86a17-16e3-4f65-9ddf-2d0bd933341d

### Asignar un usuario a un rol desde el controller Rol
POST {{Api_HostAddress}}/api/rol/a5f86a17-16e3-4f65-9ddf-2d0bd933341d/usuario/1

### Quitar un usuario a un rol desde el controller Rol
DELETE {{Api_HostAddress}}/api/rol/a5f86a17-16e3-4f65-9ddf-2d0bd933341d/usuario/1

### Eliminar rol
DELETE {{Api_HostAddress}}/api/rol/a5f86a17-16e3-4f65-9ddf-2d0bd933341d

### Eliminar usuario
DELETE {{Api_HostAddress}}/api/usuario/1